### ISSUE TITLE
Update ComboBox to 2.0

### ISSUE THREAD

**Issue by pekam** [vaadin/testbench-elements#60]
The client-side `dataProvider` and lazy loading functionality break a lot of stuff in the current TB API of ComboBox. I patched one of the methods in the ComboBox repository:
https://github.com/vaadin/vaadin-combo-box-flow/blob/master/src/test/java/com/vaadin/flow/component/combobox/ComboBoxElementUpdated.java

but all of the methods should be checked with `vaadin-combo-box-flow 2.0` (first alpha coming soon), fixed and released to be included in the same platform release where ComboBox 2.0 lands.

A lot (or maybe all) of the API should be fixable by using `filteredItems` instead of `items`. The `items`-property is not used by the Flow component at all anymore, but instead it uses the `dataProvider`-function. The `filteredItems`-property stores the currently loaded items. It will be empty until the combobox is opened, and it loads the first page. With large data sets, it will not contain all of the items until scrolling down.

**Comment by alvarezguille** [comment]
Fixed in #61 and #62
