### ISSUE TITLE
Adding TimePickerElement for vaadin-time-picker-flow

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/testbench-elements#68]
`vaadin-time-picker-flow 1.0.0` has been released and is going to be added to the platform. So, we need the `TimePickerElement` in TestBench.

**Comment by web-padawan** [comment]
`TimePickerElement` was added by https://github.com/vaadin/vaadin-time-picker-flow/pull/14/commits/4774d8edbe78ede60da7e340d706cb0ca5da865e. Closing.
