### ISSUE TITLE
Creat TBElement for ListBoxElement

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/testbench-elements#69]

**Comment by bogdanudrescu** [comment]
https://github.com/vaadin/vaadin-list-box-flow/pull/40/commits/d06c9dbbfed270a0f91ab1f07b31e6a381c3a5cf

We may start with this.

**Comment by alvarezguille** [comment]
minimum API would be `getOptions` and `selectByText`
remember to implement `implements HasLabel, HasSelectByText`

**Comment by tulioag** [comment]
PR opened: vaadin/vaadin-list-box-flow#41
